sudo: false
language: ruby
rvm:
  - 2.1.6
before_install: 
  - gem install bundler -v 1.14.6
os:
  - linux
  - osx
deploy:
  provider: rubygems
  api_key:
    secure: # Generate new key
  gem: tfmodtest
  on:
    tags: true
    repo: vistaprint/tfmodtest